# Generated by Django 3.0.4 on 2020-03-28 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_title', models.CharField(max_length=200)),
                ('cat_image', models.ImageField(blank=True, help_text='Upload only .png and.jpg', null=True, upload_to='images/cat_images')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_title', models.CharField(max_length=200)),
                ('deal_desc', models.CharField(max_length=500, null=True)),
                ('deal_image1', models.ImageField(blank=True, help_text='Upload only .png and jpg', null=True, upload_to='images/deal_images')),
                ('deal_image2', models.ImageField(blank=True, help_text='Upload only .png and jpg', null=True, upload_to='images/deal_images')),
                ('deal_image3', models.ImageField(blank=True, help_text='Upload only .png and jpg', null=True, upload_to='images/deal_images')),
                ('temp_type', models.IntegerField(blank=True, default=0)),
                ('deal_actualprice', models.IntegerField(blank=True, default=0)),
                ('deal_discount', models.IntegerField(blank=True, default=0)),
                ('deal_price', models.IntegerField(blank=True, default=0)),
                ('deal_postedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('deal_validity', models.DateTimeField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glattdeal.Category')),
                ('deal_postedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200)),
                ('supplier_email', models.CharField(max_length=200)),
                ('supplier_password', models.CharField(max_length=200)),
                ('supplier_username', models.CharField(max_length=200)),
                ('supplier_address', models.CharField(max_length=200)),
                ('supplier_contact', models.CharField(max_length=10)),
                ('supplier_details', models.CharField(max_length=500, null=True)),
                ('supplier_info', models.CharField(max_length=200, null=True)),
                ('supplier_image', models.ImageField(blank=True, help_text='Upload only .png and jpg', null=True, upload_to='images/supp_images')),
                ('supplier_starttime', models.DateTimeField(blank=True)),
                ('supplier_endtime', models.DateTimeField(blank=True)),
                ('deal_supid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glattdeal.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(blank=True, default=0)),
                ('review_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('review', models.CharField(max_length=500, null=True)),
                ('deal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glattdeal.Deal')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_id', models.CharField(max_length=100, null=True)),
                ('total_amount', models.IntegerField(blank=True, default=0)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('payment_amount', models.IntegerField(blank=True, default=0)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('txn_id', models.CharField(max_length=100, null=True)),
                ('payment_currency', models.CharField(max_length=10, null=True)),
                ('payment_status', models.CharField(max_length=10, null=True)),
                ('payer_email', models.CharField(max_length=10, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glattdeal.Supplier'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, default=0)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('total', models.IntegerField(blank=True, default=0)),
                ('deal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glattdeal.Deal')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
