# Generated by Django 3.0.4 on 2020-03-28 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glattdeal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='deal_supid',
            new_name='userid',
        ),
    ]
