# Generated by Django 3.0.4 on 2020-03-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glattdeal', '0002_auto_20200328_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier_image',
            new_name='supplier_image1',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='deal_image1',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='deal_image2',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='deal_image3',
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_image2',
            field=models.ImageField(blank=True, help_text='Upload only .png and jpg', null=True, upload_to='images/supp_images'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_image3',
            field=models.ImageField(blank=True, help_text='Upload only .png and jpg', null=True, upload_to='images/supp_images'),
        ),
    ]
