# Generated by Django 3.0.4 on 2020-03-29 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('glattdeal', '0003_auto_20200329_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_info',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_endtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_starttime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
