# Generated by Django 3.0.4 on 2020-03-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glattdeal', '0004_auto_20200329_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='supplier_id',
        ),
    ]
