# Generated by Django 3.0.4 on 2020-03-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glattdeal', '0005_remove_deal_supplier_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='temp_type',
        ),
    ]
