# Generated by Django 3.0.4 on 2020-03-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glattdeal', '0007_auto_20200329_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='deal_validity',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_endtime',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_starttime',
        ),
        migrations.AddField(
            model_name='deal',
            name='deal_enddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='deal_startdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
