# Generated by Django 3.0.4 on 2020-03-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glattdeal', '0009_auto_20200330_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
