# Generated by Django 3.0.4 on 2020-03-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glattdeal', '0016_auto_20200330_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='category',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
