# Generated by Django 3.0.4 on 2020-04-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glattdeal', '0019_payment_supplier_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='user_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user_fname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user_image',
            field=models.ImageField(blank=True, help_text='Upload only .png and jpg', null=True, upload_to='images/user_images'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user_lname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
