# Generated by Django 3.0.4 on 2020-04-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glattdeal', '0020_auto_20200404_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='item_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
